main/src/JAG.DevTest2019.WebHost/Models/LeadResultViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JAG.DevTest2019.Host.Models
{
    public class LeadResultViewModel
    {
        public long LeadId { get; set; }

        public bool IsSuccessful { get; set; }

        public string Message { get; set; }
    }
}

main/src/JAG.DevTest2019.WebHost/Models/LeadViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JAG.DevTest2019.Host.Models
{
    public class LeadViewModel
    {

        public LeadViewModel()
        {
            Results = new LeadResultViewModel();
        }

        public string TrackingCode { get; }

        [Display(Name = "Select your gender?")]
        public string Gender { get; set; }

        [Display(Name = "Select your language?")]
        public string Language { get; set; }

        [Display(Name = "Select your blood type?")]
        public string BloodType { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "You must provide a phone number")]
        [Display(Name = "Surname")]
        public string Surname { get; set; }

        public string SessionId { get; set; }

        public decimal ServiceQueriesNumber { get; set; } = 6000000;

        //public string ServicedQueriesNumberString { get { return ServiceQueriesNumber}; }
    
        [Required]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        [Display(Name = "Email Address (Valid Email)")]
        public string EmailAddress { get; set; }

        [Required]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        [Display(Name = "Contact Number (000-000-0000)")]
        public virtual string ContactNumber { get; set; }

        public List<SelectListItem> Genders { get; } = new List<SelectListItem>()
        {
            new SelectListItem()  {Text="Male", Value = "Male"},
            new SelectListItem()  {Text="Female", Value = "Female"},
        };

        public List<SelectListItem> Languages { get; } = new List<SelectListItem>()
        {
            new SelectListItem()  {Text="English", Value = "English"},
            new SelectListItem()  {Text="Afrikaans", Value = "Afrikaans"},
            new SelectListItem()  {Text="Zulu", Value = "Zulu"},
            new SelectListItem()  {Text="Xhosa", Value = "Xhosa"},
            new SelectListItem()  {Text="Sesotho ", Value = "Sesotho"},
        };

        public List<SelectListItem> BloodTypes { get; } = new List<SelectListItem>()
        {
            new SelectListItem()  {Text="O+", Value = "O+"},
            new SelectListItem()  {Text="O-", Value = "O-"},
            new SelectListItem()  {Text="A+", Value = "A+"},
            new SelectListItem()  {Text="A-", Value = "A-"},
            new SelectListItem()  {Text="B+", Value = "B+"},
            new SelectListItem()  {Text="B-", Value = "B-"},
            new SelectListItem()  {Text="AB+", Value = "AB+"},
            new SelectListItem()  {Text="AB-", Value = "AB-"},
        };

        public LeadResultViewModel Results { get; set; }
    }
}

main/src/JAG.DevTest2019.WebHost/Controllers/LeadController.cs
using JAG.DevTest2019.Host.Models;
using JAG.DevTest2019.Host.signalr.hubs;
using JAG.DevTest2019.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace JAG.DevTest2019.Host.Controllers
{
    public class LeadController : Controller
    {
        public ActionResult Index()
        {
            return View(new LeadViewModel());
        }

        public async Task<ActionResult> SubmitLead(LeadViewModel model)
        {
            //TODO: 6. Call the WebAPI service here & pass results to UI

            string apiUrl = "http://localhost:8099/api/lead/submit";

            string sessionID = HttpContext.Session.SessionID;

            LeadResponse apiResponse = new LeadResponse();

            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = await client.PostAsync<LeadViewModel>(apiUrl, model, new JsonMediaTypeFormatter());
                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    apiResponse = Newtonsoft.Json.JsonConvert.DeserializeObject<LeadResponse>(data);

                }


            }

            LeadViewModel result = new LeadViewModel()
            {
                Results = new LeadResultViewModel()
                {
                    LeadId = new Random().Next(),
                    IsSuccessful = true,

                    Message = String.Join("", apiResponse.Messages)
                }
            };

            return View("Index",result);
        }
    }
}

main/src/JAG.DevTest2019.WebHost/Views/Lead/Index.cshtml
@{
    Layout = "~/Views/shared/_LeadLayout.cshtml";
    ViewBag.Title = "Page title";
}
@using JAG.DevTest2019.Host.Models
@model LeadViewModel
@{int count = 6000000;}

@section Meta{
    <meta name="description" content="Default site" />
    <meta name="keywords" content="Default" />
}

<section id="quote" class="main-banner" style="background-image: url(/Content/Images/Banners/car-insurance.jpg)">
    <div class="slant-left col-md-9 pull-left">
        <div class="col-md-8 col-md-offset-2">
            <div class="capture-form">
                <h1 class="text-center">Insurance</h1>
                <h4>Don’t pay too much, find the best insurance quotes and start saving today!</h4>
                @*@using (Html.BeginForm("SubmitLead", "Lead", FormMethod.Post, new { id = "frmsubmit" }))
                    {*@
                @using (Ajax.BeginForm("SubmitLead", "Lead", new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess", OnFailure = "OnFailure", LoadingElementId = "loading" }, new { id = "frmsubmit" }))
                {
                    @Html.AntiForgeryToken();
                    <div id="loading">
                        @*<img src="~/Content/Images/126.gif" />*@
                    </div>
                    <div class="col-md-12">
                        <p>
                            <input type="hidden" value="@Model.TrackingCode" id="hdnTrackingCode" />

                            My name is @Html.TextBoxFor(model => model.FirstName, new { @placeholder = Html.DisplayNameFor(model => model.FirstName), @required = "required" }) @Html.TextBoxFor(model => model.Surname, new { @placeholder = Html.DisplayNameFor(model => model.Surname), @required = "required" })
                            You can contact me at @Html.TextBoxFor(model => model.EmailAddress, new { @placeholder = Html.DisplayNameFor(model => model.EmailAddress), @required = "required" }) or @Html.TextBoxFor(model => model.ContactNumber, new { @placeholder = Html.DisplayNameFor(model => model.ContactNumber)})
                            to help me save on insurance
                            I am @Html.DropDownListFor(model => model.Gender, Model.Genders, "Gender") and my language preference is
                            @Html.DropDownListFor(model => model.Language, Model.Languages, "Language")
                            and my blood type is @Html.DropDownListFor(model => model.BloodType, Model.BloodTypes, "BloodType")
                        </p>
                    </div>
                    <div class="clearfix"></div>

                    <div class="col-md-12 text-center">
                        <button type="submit" id="btnSubmit" class="orange-button">Get Quotes Now</button>
                    </div>
                }
                @if (Model.Results != null &&
                    Model.Results.IsSuccessful)
                {
                    <div class="col-md-12 text-center">
                        <img src="~/Content/Images/Products/new-success.png" height="24px" />
                        @Html.ValueFor(model => model.Results.Message)
                        <p id="signalrId"></p>
                    </div>
                }

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</section>
<div class="clearfix"></div>
<div class="container benefits-padding text-center">
    <h2>Benefits</h2>
    <div class="benefits-cols">
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-save.png" />
            <p>People saved on insurance</p>
        </div>
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-calling.png" />
            <p>99.99% were called in under 5 minutes</p>
        </div>
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-success.png" />
            <p>96% believe these stats</p>
        </div>
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-clients.png" />
            @Html.Hidden("count", 6000000)
            <p id="queriesCount">Over @Html.ValueFor(model => count) queries serviced</p>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<div id="quote" class="testimonial-banner" style="background-image: url('../../Content/Images/Banners/best-car-insurance.jpg');">
    <div class="slant-right col-md-9 pull-right">
        <div class="col-md-6 col-md-offset-3 testimonials text-center">
            <b>Getting the lowest insurance quote has never been so easy:</b>
            <p>
                <b>Joe Blogs (26 years)</b><br /><br />
                Telsa model x <br />
                Was paying R999,999.99<br />
                Now paying R99.99
            </p>
            <h2 class="highlight">Insurance saving of {lots of %}</h2>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<div class="container-blue">
    <div class="col-md-6 col-md-offset-3 text-center">
        <h1>Get a quote and</h1>
        <h1 class="green">start saving now</h1>
        <p>Get in touch to receive insurance quotes from South Africa’s top insurance companies. Getting the lowest insurance premiums has never been so easy.</p>
        <a id="lnkGetQuote" href="#quote" class="orange-button">Get a quote now</a>
    </div>
    <div class="clearfix"></div>
</div>

@section Scripts{
    <script src="~/Scripts/jquery.signalR-2.4.0.min.js"></script>
    <script src="~/signalr/hubs/"></script>
    @*<script src="Scripts/jquery.signalR-3.3.1.js"></script>*@
    <script type="text/javascript">
        $(document).ready(function () {
            $('#lnkLead').addClass('activeMenu');
        })

        function onSubmitBegin() {
            // Disable the button and hide the other image here
            // or you can hide the whole div like below
            $('#btnSubmit').hide();
        }

        function increamentServiceQueriesNumber() {
           // count = 0;
            var count = parseInt($('#count').val(), 10) + 1;
            $('#count').val(count);
            //var value = $('#count').val();
            var stringValue = 'Over ' + count.toLocaleString() + ' queries serviced';
            document.getElementById("queriesCount").innerHTML = stringValue;
        }

        setInterval(function () {
            /// call your function here
            increamentServiceQueriesNumber();
            //@Model.ServiceQueriesNumber = @Model.ServiceQueriesNumber + 1;
        }, 5000);

        $(function () {
            var jagHub = $.connection.jAGMethodHub;

            jagHub.client.respondToPage = function (message) {
                //$('#signalrId').val(htmlEncode(message));
                document.getElementById("signalrId").innerHTML = htmlEncode(message);
            };

            $.connection.hub.start().done(function () {
                $('#btnSubmit').click(function () {
                    jagHub.server.send('Lead Received');
                });
            });
        });

        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }

        //var form = $('#frmsubmit').val();
        //var fd = new FormData(form);
        //$.ajax({
        //    cache: false,
        //    async: true,
        //    type: "POST",
        //    url: 'SubmitLead',
        //    data: $('#frmsubmit').serialize(),
        //    success: function (data) {
        //        alert(data);
        //    }
        //});
        //setTimeout(increamentServiceQueriesNumber, 5000);
    </script>
}

main/src/JAG.DevTest2019.WebHost/Views/Shared/_LeadLayout.cshtml
@using System.Web.Mvc

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/favicon.ico" rel="shortcut icon">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:500,600,800" rel="stylesheet">
    <title>JAG Dev Test: @ViewBag.Title</title>
    @RenderSection("Meta", required: false)

    <!-- Styles
    ================================================== -->
    @Styles.Render("~/bundles/css")
    <link rel="stylesheet" href="~/Content/Newcustom.css">
    <style>
        .async-hide {
            opacity: 0 !important
        }
    </style>

    <!--[if IE]>
    <link rel="stylesheet" href="../Content/IEfixes.css">
    <![endif]-->
    <!--[if lt IE 9]>
    <link rel="stylesheet" href="~/Content/ltIEfixes.css">
    <![endif]-->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltips and media queries -->
    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="pre-header">
        <div class="container">
            <div class="col-md-12 pull-right number text-right">
                Need help? <a href="tel:+27113266761">011 326 6761</a>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clear"></div>
    </div>
    <nav class="navbar navbar-default" role="navigation">
        <div class="header container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a id="hypLogo" href="/">
                    <img src="~/Content/Images/logo.png" style="height:50px">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a id="lnkHome" href="/">Home</a></li>
                    <li><a id="lnkLead" href="/Lead">Leads</a></li>
                </ul>
            </div>
            <div class="clearfix"></div>
        </div>
    </nav>
    @RenderBody()
    <div class="clearfix"></div>

    <!-- JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- IE8 support of jQuery -->
    <!--[if lt IE 9]>
    <script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
    <![endif]-->
    <!--[if gte IE 9]><!-->
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <!--<![endif]-->
    <!--[if !IE]>
    <!--LeadBot-->
    @*<script type="text/javascript" src="https://popupwidget.leadflip.ai"> </script>*@
    <!--<![endif]-->

    @Scripts.Render("~/bundles/js")
    @RenderSection("Scripts", required: false)

</body>
</html>